#!/bin/bash

# Script para gerar usuarios e senhas para os sistemas
# Autor: Clayton Camargo
# Data: 06/12/2021

USUARIO=$( dialog --stdout --inputbox 'Digite o nome do usuario(ex.: clayton.camargo)' 0 45 )
SENHA=$( dialog --stdout --inputbox 'Digite a senha(ex.: yourpass#2021)' 0 45 )

htpasswd -mb /etc/apache2/dav_svn.passwd $USUARIO $SENHA

