#!/bin/bash

# Script para gerar usuarios e senhas para os sistemas
# Autor: Clayton Camargo
# Data: 12/03/2019

USUARIO=$( dialog --stdout --inputbox 'Digite o nome do usuario(ex.: dsvsft00)' 0 45 )
SENHA=$( dialog --stdout --inputbox 'Digite a senha(ex.: inj2@p29)' 0 45 )

htpasswd -mb /etc/apache2/dav_svn.passwd $USUARIO $SENHA

